conditioning:
  method: ps
  # method: fista
  params:
    scale: 2

data:
  name: recon
  accs:
    - 20
    - 4
    - 8
    - 12
    - 16
    - 24
  masks: 
    - ktGaussian
    - ktRadial
    - ktUniform
  single_file_eval: true
  dest_dir: /bigdata/CMRxRecon2024/ChallengeVal/
  # dest_dir: /bigdata/CMRxRecon2024/ChallengeTest/
  input: /input
  output: /output

measurement:
  operator:
    name: recon
  
  noise: 
    name: gaussian
    sigma: 0.05